name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command
    # and we are trying to merge from 'develop' into 'master'.
    if: ${{ contains(github.event.comment.body, '/fast-forward')
      && github.event.issue.pull_request }}
    #  && github.event.pull_request.base.ref == 'main'
    #  && github.event.pull_request.head.ref == 'develop' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
